CREATE PROCEDURE [dbo].[SP_ADD_USER]
	@ID VARCHAR (50),
	@fULLNAME VARCHAR (50),
	@PWD VARCHAR (50),
	@USERTYPE VARCHAR (50)
AS
	INSERT INTO tbl_User
	( ID,
	FULLNAME,
	PWD,
	UserType)
	VALUES
	(@ID,@fULLNAME,@PWD,@USERTYPE)
