create PROCEDURE [dbo].[SP_ADD_ORDER]
	@ID_ORDER INT,
	@DATE_ORDER DATETIME,
	@CUSTOMER_ID INT ,
	@DESCRIPTION_ORDER VARCHAR (250),
	@SALESMAN VARCHAR(75)
AS
INSERT INTO [tbl_Order]
	([ID_ORDER],
	[DATE_ORDER],
	[CUSTOMER_ID],
	[DESCRIPTION],
	[SALESMAN]
	)

	VALUES
	(@ID_ORDER,
	@DATE_ORDER,
	@CUSTOMER_ID,
	@DESCRIPTION_ORDER,
	@SALESMAN
	)
