create PROCEDURE [dbo].[SP_ADD_ORDER_DETAILS]
	@ID_PRODUCT VARCHAR(30) ,
	@ID_ORDER INT,
	@QTE INT,
	@PRICE VARCHAR (50),
	@DISCOUNT FLOAT ,
	@AMOUNT VARCHAR (50),
	@TOTAL_AMOUNT VARCHAR (50)
AS
	INSERT INTO tbl_Order_Detail
	(ID_PRODUCT,
	ID_ORDER,
	QTE,
	PRICE,
	DISCOUNT,
	AMOUNT,
	TOTAL_AMOUNT
	)
	VALUES
	(@ID_PRODUCT,
	@ID_ORDER,
	@QTE,
	@PRICE,
	@DISCOUNT,
	@AMOUNT,
	@TOTAL_AMOUNT
	)

update tbl_Products set QTE_IN_STOCK=QTE_IN_STOCK-@QTE
where ID_PRODUCT =@ID_PRODUCT