CREATE PROCEDURE [dbo].[SP_UPDATE_PRODUCT]
	@ID_CAT int ,
	@ID_PRODUCT VARCHAR(30),
	@LABEL VARCHAR (30),
	@QTE INT,
	@PRICE VARCHAR (50),
	@IMG IMAGE
AS
UPDATE tbl_Products
SET ID_CAT=@ID_CAT,
LABEL_PRODUCT=@LABEL,
QTE_IN_STOCK=@QTE,
PRICE=@PRICE,
IMAGE_PRODUCT=@IMG
WHERE ID_PRODUCT=@ID_PRODUCT

