CREATE TABLE [dbo].[tbl_Customers](
	[ID_CUSTOMER] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](25) NULL,
	[LAST_NAME] [varchar](25) NULL,
	[TEL] [nchar](15) NULL,
	[EMAIL] [varchar](25) NULL,
 [IMAGE_CUSTOMER] IMAGE NULL, 
    CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED 
(
	[ID_CUSTOMER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]